---
- name: Playbook for VPC
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Creates NAT Gateway
      ec2_vpc_nat_gateway:
        region: "{{region}}"
        subnet_id: "{{subnet_id}}"
        state: state 