
---
- hosts: localhost
  tasks:
    - name: Create Private Subnet1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        cidr: "{{cidr}}"
    - name: Create Private Subnet2
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        cidr: "{{cidr}}"
    - name: Create Private Subnet3
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        cidr: "{{cidr}}"