---
- hosts: localhost
  vars_files: 
  - region.yaml
  tasks: 
    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: "{{region}}"
        filters:
          "tag:Task": VPC
      register: VPC1

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{VPC1.vpcs[0].id}}"
        region: "{{region}}"
        tags:
          Name: Public
        subnets:
          - "{{Pub_Subnet1}}"
          - "{{Pub_Subnet2}}"
          - "{{Pub_Subnet3}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw.gateway_id}}"
      register: public_route_table
      
    - name: Set up NAT-protected route table
      ec2_vpc_route_table:
        vpc_id: "{{VPC1.vpcs[0].id}}"
        region: "{{region}}"
        tags:
          Name: Internal
        subnets:
          - "{{Priv_Subnet1}}"
          - "{{Priv_Subnet2}}"
          - "{{Priv_Subnet3}}"
        routes:
          - dest: 0.0.0.0/0
            instance_id: "{{nat.instance_id}}"
      register: nat


    - name: Debug
      debug:
        msg:  "{{public_route_table}}"