---
- name: Creates VPC
  hosts: localhost
  vars_files: 
  - input.yaml
  tasks:
  - name: Creates VPC
    ec2_vpc_net:
      name: VPC_project_Team
      cidr_block: "{{cidr}}"
      region: "{{region}}"
      state: present
 
